### PR TITLE
Incremental build

### PR DESCRIPTION
**Pull request by TrySound**
ref #291

### CODE REVIEW

**Comment by TrySound** [comment]
Maybe we don't need to snapshot js? Such snapshots are not readable.

**Comment by tivac** [comment]
No, but they're very useful to ensure that the values returned by the loader are correct.

This is cool, I have a few stylistic nits but otherwise lgtm. I'll try to get it landed tomorrow.

**Comment by tivac** [comment]
Published in `modular-css-webpack@4.4.0`

**Comment by TrySound** [comment]
Nice, Thanks!

**Pull request merged**
