### PR TITLE
fix: don't assume `plugin` key on messages

### PR DESCRIPTION
**Pull request by jquense**
when passing custom plugins you may get messages that don't have this key

### CODE REVIEW

**Comment by tivac** [comment]
Oof, good catch!

**Comment by jquense** [comment]
@tivac could we get a release on for this :)

**Comment by tivac** [comment]
As soon as I can, had my hands full for work for a bit here :(

**Comment by tivac** [comment]
Just published this as `v25.3.1`

**Comment by jquense** [comment]
awesome thanks!

**Pull request merged**
