### PR TITLE
Use ES2015 exports in webpack

### LINKED ISSUE #280: webpack namedExports mode
Webpack2 has es modules support and can validate existing exports of (!) harmony modules. The module should contain at least one import or export statement.

```js
module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'dist/bundle.js'
    },
    module: {
        strictExportPresence: true
    }
};
```

```
ERROR in ./src/index.js
3:12-23 "export 'namedExport' was not found in './mod.js'
```

Empty output file may contains like this
```js
export const __cssModules__ = true; // export to identify file as harmony contained and enable errors
```
```js
// index.js
import * as style from './myStyle.css';
console.log(style.myClass);
```
```
// myStyle.css
// before
.myClass {}

// after
export const __cssModules = true;
// ... some loading code
export const myClass = 'hash-123456';
```

### PR DESCRIPTION
**Pull request by tivac**
This is mostly a copy/paste of the rollup code. It could be extracted out into some sort of shared package but it's just different enough to not make it worth that work.

@TrySound, this about what you were looking for?

Fixes #280

### CODE REVIEW

**Comment by TrySound** [comment]
Are you sure imports is a good idea for custom format? Do they make sense here?

**Comment by TrySound** [comment]
About warning. User can want to use only default exports without validation, but with whatever they want class names. There could be an option for this.

**Comment by TrySound** [comment]
Also it would be a good to have a test about not found export warning. Just to be sure it works.

**Comment by tivac** [comment]
> Are you sure imports is a good idea for custom format? Do they make sense here?

I'm not sure what you're asking here, sorry. ES2015 module semantics are a great fit for this.

> About warning. User can want to use only default exports without validation, but with whatever they want class names. There could be an option for this.

I'm ambivalent about this, feel like it could come later.

> Also it would be a good to have a test about not found export warning. Just to be sure it works.

I don't see how the loader could determine if an invalid export had been imported, but I don't know the webpack API super-well. If you have any advice on how to add logic & a test-case for that I'm interested in adding it. Otherwise it'll have to silently fail.

**Comment by tivac** [comment]
(rebased against changes in `master` to remove merge conflicts)

**Comment by TrySound** [comment]
> I'm not sure what you're asking here, sorry. ES2015 module semantics are a great fit for this.
Some guys use webpack like import * as css from 'modular-css/lodash!./file.css';
If you will add own imports, this case will break there usage. You still add those files as dependencies, so there's not a reason to add it as statement too.

> I don't see how the loader could determine if an invalid export had been imported, but I don't know the webpack API super-well. If you have any advice on how to add logic & a test-case for that I'm interested in adding it. Otherwise it'll have to silently fail.

With `strictExportPresence` like I mentioned in issue webpack can throw an error if you are trying to access to not existing export.

**Comment by tivac** [comment]
Oh, sorry. The injection of `import` statements is a holdover from the rollup code I based this on. I'll remove that.

I can't find real docs on `strictExportPresence`, just this PR https://github.com/webpack/webpack/pull/4348 I'll play around w/ it some and see if that's something that requires any support from my loader.

**Comment by TrySound** [comment]
Yeah, I found it in that PR and a source code. Documentation of webpack is not whole. But this feature looks stable. I guess your loader can be one of the first who document it ))

**Comment by tivac** [comment]
Based on a quick flip through the webpack code it looks like `strictExportPresence` is an entirely user-supplied option. I'm not going to do anything like force it to be true, that's up to users to care about IMO.

**Comment by tivac** [comment]
This is live in `modular-css-webpack@4.2.0`

**Comment by TrySound** [comment]
Thanks

**Pull request merged**
