### PR TITLE
feat: Support escaped characters in composed class names

### PR DESCRIPTION
**Pull request by jquense**
# Description
Support for more valid classnames, helpful with tailwindCSS which uses classes like `hover:bg-red`

implementation borrowed mostly from https://github.com/pegjs/pegjs/blob/v0.10.0/examples/css.pegjs

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tivac** [comment]
Thanks!

**Comment by jquense** [comment]
thank you 👍 any chance of getting a release soon?

**Comment by tivac** [comment]
I was waiting to clump it together with somethin else, but uh... I don't remember what that was going to be. I'll cut a release in a minute here.

**Comment by tivac** [comment]
released in `25.7.0`

**Pull request merged**
