### PR TITLE
feat: more composition errors

### LINKED ISSUE #918: Throw when composing within non-class rules
### Describe the bug

When composing within rule with a complex selector like `.complex.selector` modular-css throws an error:
`CssSyntaxError: modular-css-composition: (...) Only simple singular selectors may use composition`.

OTOH it doesn't throw for other cases of misuse. 
<details>
<summary>Incorrect use of the composition.</summary>

```css
.fooga { color: red; }

html { composes: fooga; }

.class:focus { composes: fooga; }

.class::after { composes: fooga; }

@media (all) {
    html { composes: fooga; }
}

/* etc. */
```
</details>

I suppose modular-css could throw an error every time a `compose` is incorrectly used.

### Reproduction

https://m-css.com/repl/#NrBEHoDMEsBsFMBMA6AtgYwM6dAGlMpAPZEDmAhgAQDel6RsRATgFyVPwAmA3JQL4AdAHbDhACwAuqWDWGV5dIqgAORTPExtiZct2GCRQ5OljlsLYugCumWUIWKVajVpIU9Qg8OOnzLcpAS8Ex2DvRO6pqU2u76okIAAqhc0FQAFOSwsACUoQqS0nkO8uGqka46Hg4GXkalCAAeyOoI6BLMRY5lLtFuunFCoAC6Q0A

### Logs

_No response_

### System Info

```shell
-
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by tivac**
Fixes #918

### CODE REVIEW

**Comment by tivac** [comment]
@plesiecki is this what you were asking for in #918?

**Review by plesiecki — APPROVED** [review]
Lovely, LGTM 🧐

**Review by plesiecki — COMMENTED** [review]
Shall we consider `composes` within an at-rule?

**Comment by plesiecki** [comment]
@tivac WDYT?

**Comment by tivac** [comment]
Sorry, I held off on this for a bit since it's a breaking change and the psuedo change is a bit annoying for how I'm used m-css in the past.

I think preventing from composing within a @-rule makes sense, not sure when I'll be able to get to that though.

**Comment by plesiecki** [comment]
Lovely, thanks ❤️

**Pull request merged**
