### PR TITLE
fix: webpack 4

### PR DESCRIPTION
**Pull request by getkey**
This PR fixes API changes introduced in Webpack 4.

### CODE REVIEW

**Comment by tivac** [comment]
@getkey Thanks! Is this actually testing against `webpack@4`?

**Comment by getkey** [comment]
Right, I forgot to run the tests. I also need to update the devDependency. I'll do it tomorrow because I'm in bed now. ;-)

**Comment by getkey** [comment]
A bunch of tests are failing because webpack@4 prepends `./dist/` to the output path.

**Comment by tivac** [comment]
Neat, I'll take a look when I get into the office in a bit. May just need to tweak the test webpack configs, hopefully.

**Comment by tivac** [comment]
Most of the failures seem to be around `webpack@4` defaulting to `production` mode. I'm working on finalizing the test cleanup in a branch that I'll merge manually.

https://github.com/tivac/modular-css/tree/pr/413

Having some weird output from the test that runs webpack multiple times w/ changed file contents though, will need to investigate that further I think.

**Comment by tivac** [comment]
Looks like `compiler.plugin("invalid")` is no longer triggering, so my plugin happily barfs out the cached contents forever.

😒 

I'll need to do some research on what replaced that event. I love major version upgrades!

**Comment by deflock** [comment]
`compiler.hooks.invalid.tap(...)`

**Comment by tivac** [comment]
@deflock I tried that, it never seems to get invoked either. 😒

**Comment by tivac** [comment]
Tracked it down, fixing the last few Travis failures now.

**Comment by tivac** [comment]
@getkey published as `modular-css-webpack@8.2.0`

Thanks again! :tada:

**Comment by getkey** [comment]
Awesome, thanks @tivac!

If I understand correctly #409, support for Webpack 2 & 3 is dropped for the moment, right?

**Comment by tivac** [comment]
AFAIK this version should be compatible with webpack 2-4, though testing it against multiple versions is challenge.

**Comment by getkey** [comment]
Ah alright, yes! :slightly_smiling_face:

**Pull request merged**
