### PR TITLE
Fix json option handling

### PR DESCRIPTION
**Pull request by plesiecki**

### CODE REVIEW

**Comment by tivac** [comment]
The existing test for this functionality is passing, can you provide some more details about the issue this is solving?

**Comment by plesiecki** [comment]
Passing `json` option doesn't work for me. I looks like `results.opts.json` is always undefined:
https://github.com/tivac/modular-css/blob/master/packages/postcss/postcss.js#L13-L17

**Comment by tivac** [comment]
Hmm, I'll poke at it. Want to understand what the tests are missing before any chances get made. Thanks for the PR!

**Comment by tivac** [comment]
I just wrote https://github.com/tivac/modular-css/commit/04b8adf6464861453645cd949e9ea31b2c4bab84 to ensure that this works with postcss and the tests are covering it. Seems like it's working as intended.

Can you show me how you're using the postcss plugin?

**Comment by plesiecki** [comment]
Standard just like this
```js
const postcss = require('gulp-postcss')
const modularCSS = require('postcss-modular-css')

//...
.pipe(postcss([
    modularCSS({json: 'main.json'})
]))
```

**Comment by tivac** [comment]
Oh, it's because of how `gulp-postcss` creates the PostCSS processor.

This should work for now:

```js
.pipe(postcss([ modularCSS() ], { json : "main.json" }))
```

I'm going to take a slightly tweaked approach to this so that it accepts the `json` argument from either spot. Thanks for the PR!

**Comment by tivac** [comment]
@plesiecki this is fixed in `postcss-modular-css@4.2.3`, sorry for the trouble and thanks again for the investigation and PR!

**Comment by plesiecki** [comment]
Well this PR was worst PR ever but I'm glad I could help ;)

**Pull request closed without merging**
