### PR TITLE
feat: exportGlobals option in core

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/tivac/modular-css/issues/284

### CODE REVIEW

**Comment by TrySound** [comment]
@tivac Looks like tests failed not becaise of PR.

**Comment by tivac** [comment]
Re-ran the tests, this looks good. Thanks!

**Comment by TrySound** [comment]
Do you have a plan for minor release?

**Comment by tivac** [comment]
Probably 6-7 hours away? I'm at work atm and trying to get actual employer things done.

**Comment by tivac** [comment]
Just published:

- `modular-cssify@4.4.0`
- `modular-css@4.5.0`
- `modular-css-cli@4.2.0`
- `modular-css-core@4.3.0`
- `modular-css-glob@4.2.0`
- `modular-css-paths@4.2.6`
- `postcss-modular-css@4.3.0`
- `modular-css-rollup@4.2.0`
- `modular-css-webpack@4.3.0`

**Pull request merged**
