### PR TITLE
Recursive remove

### PR DESCRIPTION
**Pull request by TrySound**
Ref #297 
Recursion with state mutating can be dangerous sometimes :)

### CODE REVIEW

**Comment by TrySound** [comment]
Em... Why I got correct results on windows?

**Comment by TrySound** [comment]
Maybe it's `resolve-from` different behavior? Sindre uses node resolver under the hood.

**Comment by TrySound** [comment]
Uh, npm i :)

**Comment by TrySound** [comment]
Okay. API was changed, you didn't update usage, but updated test cases.

**Comment by tivac** [comment]
Good catch, thanks!

**Comment by tivac** [comment]
Published in `5.1.1`

**Pull request merged**
